- hosts:
  - local
  vars_files:
    - ../vars/var_defs.yaml
  tasks:
  - name: "Print on condition true"
    debug:
      msg: "Active"
    when: my_cond
  - name: "Print on condition false"
    debug:
      msg: "Not Active"
    when: not my_cond

